/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppSetting: typeof import('./../src/layout/main-layout/components/AppSetting.vue')['default']
    IconCommunity: typeof import('./../src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../src/components/icons/IconSupport.vue')['default']
    IconTablerCircleDot: typeof import('./../src/components/icons/IconTablerCircleDot.vue')['default']
    IconTooling: typeof import('./../src/components/icons/IconTooling.vue')['default']
    LoginBox: typeof import('./../src/components/login-box/LoginBox.vue')['default']
    Logo: typeof import('./../src/components/logo/Logo.vue')['default']
    MainLayout: typeof import('./../src/layout/main-layout/MainLayout.vue')['default']
    MenuBar: typeof import('./../src/layout/main-layout/components/MenuBar.vue')['default']
    MenuItem: typeof import('./../src/layout/main-layout/components/MenuItem.vue')['default']
    NavRecordBar: typeof import('./../src/layout/main-layout/components/NavRecordBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SCascader: typeof import('./../src/components/vs-search/components/s-cascader/s-cascader.vue')['default']
    SDate: typeof import('./../src/components/vs-search/components/s-date/s-date.vue')['default']
    SInput: typeof import('./../src/components/vs-search/components/s-input/s-input.vue')['default']
    SInputNumber: typeof import('./../src/components/vs-search/components/s-input-number/s-input-number.vue')['default']
    SSelect: typeof import('./../src/components/vs-search/components/s-select/s-select.vue')['default']
    STime: typeof import('./../src/components/vs-search/components/s-time/s-time.vue')['default']
    STreeSelect: typeof import('./../src/components/vs-search/components/s-tree-select/s-tree-select.vue')['default']
    TableColumn: typeof import('./../src/components/vs-table/table-column.vue')['default']
    TopBar: typeof import('./../src/layout/main-layout/components/TopBar.vue')['default']
    ViewWrapper: typeof import('./../src/components/view-wrapper/ViewWrapper.vue')['default']
    VsSearch: typeof import('./../src/components/vs-search/VsSearch.vue')['default']
    VsTable: typeof import('./../src/components/vs-table/VsTable.vue')['default']
    VsTreeSelect: typeof import('./../src/components/vs-tree-select/VsTreeSelect.vue')['default']
  }
}
