import { http } from '@/utils/http'

export async function queryUserInfo() {
  try {
    const { data } = await http({
      method: 'get',
      url: '/mock/user-info.json?t=' + +new Date()
    })
    return data as {
      userId?: number
      userName?: string
    }
  } catch (error) {
    console.error('queryUserInfo ->', error)
  }
}

export async function queryMenuData() {
  try {
    const { data } = await http({
      method: 'get',
      url: '/mock/menu-data.json?t=' + +new Date()
    })
    return data as VsMenuDataItem[]
  } catch (error) {
    console.error('queryMenuData ->', error)
  }
}

export async function queryRepos() {
  try {
    const res = await fetch('https://api.github.com/users/vsdeeper/repos', {
      method: 'get'
    })
    if (res.status === 403) throw new Error('获取数据异常')
    else return (await res.json()) as Record<string, any>[]
  } catch (error) {
    return [
      {
        id: 760382729,
        node_id: 'R_kgDOLVKFCQ',
        name: 'nestjs-demo',
        full_name: 'vsdeeper/nestjs-demo',
        private: false,
        owner: {
          login: 'vsdeeper',
          id: 15762056,
          node_id: 'MDQ6VXNlcjE1NzYyMDU2',
          avatar_url: 'https://avatars.githubusercontent.com/u/15762056?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/vsdeeper',
          html_url: 'https://github.com/vsdeeper',
          followers_url: 'https://api.github.com/users/vsdeeper/followers',
          following_url: 'https://api.github.com/users/vsdeeper/following{/other_user}',
          gists_url: 'https://api.github.com/users/vsdeeper/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/vsdeeper/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/vsdeeper/subscriptions',
          organizations_url: 'https://api.github.com/users/vsdeeper/orgs',
          repos_url: 'https://api.github.com/users/vsdeeper/repos',
          events_url: 'https://api.github.com/users/vsdeeper/events{/privacy}',
          received_events_url: 'https://api.github.com/users/vsdeeper/received_events',
          type: 'User',
          site_admin: false
        },
        html_url: 'https://github.com/vsdeeper/nestjs-demo',
        description: 'A demo about nestjs development.',
        fork: false,
        url: 'https://api.github.com/repos/vsdeeper/nestjs-demo',
        forks_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/forks',
        keys_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/keys{/key_id}',
        collaborators_url:
          'https://api.github.com/repos/vsdeeper/nestjs-demo/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/teams',
        hooks_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/hooks',
        issue_events_url:
          'https://api.github.com/repos/vsdeeper/nestjs-demo/issues/events{/number}',
        events_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/events',
        assignees_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/assignees{/user}',
        branches_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/branches{/branch}',
        tags_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/tags',
        blobs_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/languages',
        stargazers_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/stargazers',
        contributors_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/contributors',
        subscribers_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/subscribers',
        subscription_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/subscription',
        commits_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/comments{/number}',
        issue_comment_url:
          'https://api.github.com/repos/vsdeeper/nestjs-demo/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/contents/{+path}',
        compare_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/merges',
        archive_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/downloads',
        issues_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/issues{/number}',
        pulls_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/milestones{/number}',
        notifications_url:
          'https://api.github.com/repos/vsdeeper/nestjs-demo/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/labels{/name}',
        releases_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/releases{/id}',
        deployments_url: 'https://api.github.com/repos/vsdeeper/nestjs-demo/deployments',
        created_at: '2024-02-20T10:12:27Z',
        updated_at: '2024-07-14T09:21:30Z',
        pushed_at: '2024-02-27T08:39:59Z',
        git_url: 'git://github.com/vsdeeper/nestjs-demo.git',
        ssh_url: 'git@github.com:vsdeeper/nestjs-demo.git',
        clone_url: 'https://github.com/vsdeeper/nestjs-demo.git',
        svn_url: 'https://github.com/vsdeeper/nestjs-demo',
        homepage: '',
        size: 82,
        stargazers_count: 0,
        watchers_count: 0,
        language: 'TypeScript',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        has_discussions: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: null,
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [],
        visibility: 'public',
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: 'master'
      },
      {
        id: 739740362,
        node_id: 'R_kgDOLBeKyg',
        name: 'visual-development',
        full_name: 'vsdeeper/visual-development',
        private: false,
        owner: {
          login: 'vsdeeper',
          id: 15762056,
          node_id: 'MDQ6VXNlcjE1NzYyMDU2',
          avatar_url: 'https://avatars.githubusercontent.com/u/15762056?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/vsdeeper',
          html_url: 'https://github.com/vsdeeper',
          followers_url: 'https://api.github.com/users/vsdeeper/followers',
          following_url: 'https://api.github.com/users/vsdeeper/following{/other_user}',
          gists_url: 'https://api.github.com/users/vsdeeper/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/vsdeeper/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/vsdeeper/subscriptions',
          organizations_url: 'https://api.github.com/users/vsdeeper/orgs',
          repos_url: 'https://api.github.com/users/vsdeeper/repos',
          events_url: 'https://api.github.com/users/vsdeeper/events{/privacy}',
          received_events_url: 'https://api.github.com/users/vsdeeper/received_events',
          type: 'User',
          site_admin: false
        },
        html_url: 'https://github.com/vsdeeper/visual-development',
        description: 'Tools for visual development through abstract configuration.',
        fork: false,
        url: 'https://api.github.com/repos/vsdeeper/visual-development',
        forks_url: 'https://api.github.com/repos/vsdeeper/visual-development/forks',
        keys_url: 'https://api.github.com/repos/vsdeeper/visual-development/keys{/key_id}',
        collaborators_url:
          'https://api.github.com/repos/vsdeeper/visual-development/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/vsdeeper/visual-development/teams',
        hooks_url: 'https://api.github.com/repos/vsdeeper/visual-development/hooks',
        issue_events_url:
          'https://api.github.com/repos/vsdeeper/visual-development/issues/events{/number}',
        events_url: 'https://api.github.com/repos/vsdeeper/visual-development/events',
        assignees_url: 'https://api.github.com/repos/vsdeeper/visual-development/assignees{/user}',
        branches_url: 'https://api.github.com/repos/vsdeeper/visual-development/branches{/branch}',
        tags_url: 'https://api.github.com/repos/vsdeeper/visual-development/tags',
        blobs_url: 'https://api.github.com/repos/vsdeeper/visual-development/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/vsdeeper/visual-development/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/vsdeeper/visual-development/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/vsdeeper/visual-development/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/vsdeeper/visual-development/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/vsdeeper/visual-development/languages',
        stargazers_url: 'https://api.github.com/repos/vsdeeper/visual-development/stargazers',
        contributors_url: 'https://api.github.com/repos/vsdeeper/visual-development/contributors',
        subscribers_url: 'https://api.github.com/repos/vsdeeper/visual-development/subscribers',
        subscription_url: 'https://api.github.com/repos/vsdeeper/visual-development/subscription',
        commits_url: 'https://api.github.com/repos/vsdeeper/visual-development/commits{/sha}',
        git_commits_url:
          'https://api.github.com/repos/vsdeeper/visual-development/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/vsdeeper/visual-development/comments{/number}',
        issue_comment_url:
          'https://api.github.com/repos/vsdeeper/visual-development/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/vsdeeper/visual-development/contents/{+path}',
        compare_url:
          'https://api.github.com/repos/vsdeeper/visual-development/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/vsdeeper/visual-development/merges',
        archive_url:
          'https://api.github.com/repos/vsdeeper/visual-development/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/vsdeeper/visual-development/downloads',
        issues_url: 'https://api.github.com/repos/vsdeeper/visual-development/issues{/number}',
        pulls_url: 'https://api.github.com/repos/vsdeeper/visual-development/pulls{/number}',
        milestones_url:
          'https://api.github.com/repos/vsdeeper/visual-development/milestones{/number}',
        notifications_url:
          'https://api.github.com/repos/vsdeeper/visual-development/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/vsdeeper/visual-development/labels{/name}',
        releases_url: 'https://api.github.com/repos/vsdeeper/visual-development/releases{/id}',
        deployments_url: 'https://api.github.com/repos/vsdeeper/visual-development/deployments',
        created_at: '2024-01-06T11:59:52Z',
        updated_at: '2024-06-29T08:33:26Z',
        pushed_at: '2024-06-29T08:33:24Z',
        git_url: 'git://github.com/vsdeeper/visual-development.git',
        ssh_url: 'git@github.com:vsdeeper/visual-development.git',
        clone_url: 'https://github.com/vsdeeper/visual-development.git',
        svn_url: 'https://github.com/vsdeeper/visual-development',
        homepage: '',
        size: 761,
        stargazers_count: 0,
        watchers_count: 0,
        language: 'Vue',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: false,
        has_pages: false,
        has_discussions: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: {
          key: 'mit',
          name: 'MIT License',
          spdx_id: 'MIT',
          url: 'https://api.github.com/licenses/mit',
          node_id: 'MDc6TGljZW5zZTEz'
        },
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [],
        visibility: 'public',
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: 'master'
      },
      {
        id: 761554160,
        node_id: 'R_kgDOLWRk8A',
        name: 'vsdeeper',
        full_name: 'vsdeeper/vsdeeper',
        private: false,
        owner: {
          login: 'vsdeeper',
          id: 15762056,
          node_id: 'MDQ6VXNlcjE1NzYyMDU2',
          avatar_url: 'https://avatars.githubusercontent.com/u/15762056?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/vsdeeper',
          html_url: 'https://github.com/vsdeeper',
          followers_url: 'https://api.github.com/users/vsdeeper/followers',
          following_url: 'https://api.github.com/users/vsdeeper/following{/other_user}',
          gists_url: 'https://api.github.com/users/vsdeeper/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/vsdeeper/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/vsdeeper/subscriptions',
          organizations_url: 'https://api.github.com/users/vsdeeper/orgs',
          repos_url: 'https://api.github.com/users/vsdeeper/repos',
          events_url: 'https://api.github.com/users/vsdeeper/events{/privacy}',
          received_events_url: 'https://api.github.com/users/vsdeeper/received_events',
          type: 'User',
          site_admin: false
        },
        html_url: 'https://github.com/vsdeeper/vsdeeper',
        description: 'Personal homepage project.',
        fork: false,
        url: 'https://api.github.com/repos/vsdeeper/vsdeeper',
        forks_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/forks',
        keys_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/keys{/key_id}',
        collaborators_url:
          'https://api.github.com/repos/vsdeeper/vsdeeper/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/teams',
        hooks_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/hooks',
        issue_events_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/issues/events{/number}',
        events_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/events',
        assignees_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/assignees{/user}',
        branches_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/branches{/branch}',
        tags_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/tags',
        blobs_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/languages',
        stargazers_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/stargazers',
        contributors_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/contributors',
        subscribers_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/subscribers',
        subscription_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/subscription',
        commits_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/comments{/number}',
        issue_comment_url:
          'https://api.github.com/repos/vsdeeper/vsdeeper/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/contents/{+path}',
        compare_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/merges',
        archive_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/downloads',
        issues_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/issues{/number}',
        pulls_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/milestones{/number}',
        notifications_url:
          'https://api.github.com/repos/vsdeeper/vsdeeper/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/labels{/name}',
        releases_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/releases{/id}',
        deployments_url: 'https://api.github.com/repos/vsdeeper/vsdeeper/deployments',
        created_at: '2024-02-22T03:33:41Z',
        updated_at: '2024-07-14T09:42:48Z',
        pushed_at: '2024-05-14T04:50:07Z',
        git_url: 'git://github.com/vsdeeper/vsdeeper.git',
        ssh_url: 'git@github.com:vsdeeper/vsdeeper.git',
        clone_url: 'https://github.com/vsdeeper/vsdeeper.git',
        svn_url: 'https://github.com/vsdeeper/vsdeeper',
        homepage: '',
        size: 9,
        stargazers_count: 0,
        watchers_count: 0,
        language: null,
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        has_discussions: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: null,
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [],
        visibility: 'public',
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: 'master'
      },
      {
        id: 793063652,
        node_id: 'R_kgDOL0Uw5A',
        name: 'vsdeeper.github.io',
        full_name: 'vsdeeper/vsdeeper.github.io',
        private: false,
        owner: {
          login: 'vsdeeper',
          id: 15762056,
          node_id: 'MDQ6VXNlcjE1NzYyMDU2',
          avatar_url: 'https://avatars.githubusercontent.com/u/15762056?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/vsdeeper',
          html_url: 'https://github.com/vsdeeper',
          followers_url: 'https://api.github.com/users/vsdeeper/followers',
          following_url: 'https://api.github.com/users/vsdeeper/following{/other_user}',
          gists_url: 'https://api.github.com/users/vsdeeper/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/vsdeeper/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/vsdeeper/subscriptions',
          organizations_url: 'https://api.github.com/users/vsdeeper/orgs',
          repos_url: 'https://api.github.com/users/vsdeeper/repos',
          events_url: 'https://api.github.com/users/vsdeeper/events{/privacy}',
          received_events_url: 'https://api.github.com/users/vsdeeper/received_events',
          type: 'User',
          site_admin: false
        },
        html_url: 'https://github.com/vsdeeper/vsdeeper.github.io',
        description: 'Personal github.io blog.',
        fork: false,
        url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io',
        forks_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/forks',
        keys_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/keys{/key_id}',
        collaborators_url:
          'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/teams',
        hooks_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/hooks',
        issue_events_url:
          'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/issues/events{/number}',
        events_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/events',
        assignees_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/assignees{/user}',
        branches_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/branches{/branch}',
        tags_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/tags',
        blobs_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/languages',
        stargazers_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/stargazers',
        contributors_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/contributors',
        subscribers_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/subscribers',
        subscription_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/subscription',
        commits_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/commits{/sha}',
        git_commits_url:
          'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/comments{/number}',
        issue_comment_url:
          'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/contents/{+path}',
        compare_url:
          'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/merges',
        archive_url:
          'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/downloads',
        issues_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/issues{/number}',
        pulls_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/pulls{/number}',
        milestones_url:
          'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/milestones{/number}',
        notifications_url:
          'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/labels{/name}',
        releases_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/releases{/id}',
        deployments_url: 'https://api.github.com/repos/vsdeeper/vsdeeper.github.io/deployments',
        created_at: '2024-04-28T10:21:21Z',
        updated_at: '2024-07-14T09:45:02Z',
        pushed_at: '2024-06-29T10:07:33Z',
        git_url: 'git://github.com/vsdeeper/vsdeeper.github.io.git',
        ssh_url: 'git@github.com:vsdeeper/vsdeeper.github.io.git',
        clone_url: 'https://github.com/vsdeeper/vsdeeper.github.io.git',
        svn_url: 'https://github.com/vsdeeper/vsdeeper.github.io',
        homepage: '',
        size: 1192,
        stargazers_count: 0,
        watchers_count: 0,
        language: 'Vue',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: true,
        has_discussions: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: null,
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [],
        visibility: 'public',
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: 'master'
      },
      {
        id: 766086435,
        node_id: 'R_kgDOLamNIw',
        name: 'vswift',
        full_name: 'vsdeeper/vswift',
        private: false,
        owner: {
          login: 'vsdeeper',
          id: 15762056,
          node_id: 'MDQ6VXNlcjE1NzYyMDU2',
          avatar_url: 'https://avatars.githubusercontent.com/u/15762056?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/vsdeeper',
          html_url: 'https://github.com/vsdeeper',
          followers_url: 'https://api.github.com/users/vsdeeper/followers',
          following_url: 'https://api.github.com/users/vsdeeper/following{/other_user}',
          gists_url: 'https://api.github.com/users/vsdeeper/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/vsdeeper/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/vsdeeper/subscriptions',
          organizations_url: 'https://api.github.com/users/vsdeeper/orgs',
          repos_url: 'https://api.github.com/users/vsdeeper/repos',
          events_url: 'https://api.github.com/users/vsdeeper/events{/privacy}',
          received_events_url: 'https://api.github.com/users/vsdeeper/received_events',
          type: 'User',
          site_admin: false
        },
        html_url: 'https://github.com/vsdeeper/vswift',
        description: 'A quick development package based on the monorepo architecture.',
        fork: false,
        url: 'https://api.github.com/repos/vsdeeper/vswift',
        forks_url: 'https://api.github.com/repos/vsdeeper/vswift/forks',
        keys_url: 'https://api.github.com/repos/vsdeeper/vswift/keys{/key_id}',
        collaborators_url:
          'https://api.github.com/repos/vsdeeper/vswift/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/vsdeeper/vswift/teams',
        hooks_url: 'https://api.github.com/repos/vsdeeper/vswift/hooks',
        issue_events_url: 'https://api.github.com/repos/vsdeeper/vswift/issues/events{/number}',
        events_url: 'https://api.github.com/repos/vsdeeper/vswift/events',
        assignees_url: 'https://api.github.com/repos/vsdeeper/vswift/assignees{/user}',
        branches_url: 'https://api.github.com/repos/vsdeeper/vswift/branches{/branch}',
        tags_url: 'https://api.github.com/repos/vsdeeper/vswift/tags',
        blobs_url: 'https://api.github.com/repos/vsdeeper/vswift/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/vsdeeper/vswift/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/vsdeeper/vswift/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/vsdeeper/vswift/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/vsdeeper/vswift/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/vsdeeper/vswift/languages',
        stargazers_url: 'https://api.github.com/repos/vsdeeper/vswift/stargazers',
        contributors_url: 'https://api.github.com/repos/vsdeeper/vswift/contributors',
        subscribers_url: 'https://api.github.com/repos/vsdeeper/vswift/subscribers',
        subscription_url: 'https://api.github.com/repos/vsdeeper/vswift/subscription',
        commits_url: 'https://api.github.com/repos/vsdeeper/vswift/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/vsdeeper/vswift/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/vsdeeper/vswift/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/vsdeeper/vswift/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/vsdeeper/vswift/contents/{+path}',
        compare_url: 'https://api.github.com/repos/vsdeeper/vswift/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/vsdeeper/vswift/merges',
        archive_url: 'https://api.github.com/repos/vsdeeper/vswift/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/vsdeeper/vswift/downloads',
        issues_url: 'https://api.github.com/repos/vsdeeper/vswift/issues{/number}',
        pulls_url: 'https://api.github.com/repos/vsdeeper/vswift/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/vsdeeper/vswift/milestones{/number}',
        notifications_url:
          'https://api.github.com/repos/vsdeeper/vswift/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/vsdeeper/vswift/labels{/name}',
        releases_url: 'https://api.github.com/repos/vsdeeper/vswift/releases{/id}',
        deployments_url: 'https://api.github.com/repos/vsdeeper/vswift/deployments',
        created_at: '2024-03-02T09:53:42Z',
        updated_at: '2024-07-20T08:20:58Z',
        pushed_at: '2024-07-20T08:20:55Z',
        git_url: 'git://github.com/vsdeeper/vswift.git',
        ssh_url: 'git@github.com:vsdeeper/vswift.git',
        clone_url: 'https://github.com/vsdeeper/vswift.git',
        svn_url: 'https://github.com/vsdeeper/vswift',
        homepage: '',
        size: 2559,
        stargazers_count: 0,
        watchers_count: 0,
        language: 'Vue',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        has_discussions: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: {
          key: 'mit',
          name: 'MIT License',
          spdx_id: 'MIT',
          url: 'https://api.github.com/licenses/mit',
          node_id: 'MDc6TGljZW5zZTEz'
        },
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [],
        visibility: 'public',
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: 'master'
      },
      {
        id: 443267629,
        node_id: 'R_kgDOGmu6LQ',
        name: 'vswift-base',
        full_name: 'vsdeeper/vswift-base',
        private: false,
        owner: {
          login: 'vsdeeper',
          id: 15762056,
          node_id: 'MDQ6VXNlcjE1NzYyMDU2',
          avatar_url: 'https://avatars.githubusercontent.com/u/15762056?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/vsdeeper',
          html_url: 'https://github.com/vsdeeper',
          followers_url: 'https://api.github.com/users/vsdeeper/followers',
          following_url: 'https://api.github.com/users/vsdeeper/following{/other_user}',
          gists_url: 'https://api.github.com/users/vsdeeper/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/vsdeeper/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/vsdeeper/subscriptions',
          organizations_url: 'https://api.github.com/users/vsdeeper/orgs',
          repos_url: 'https://api.github.com/users/vsdeeper/repos',
          events_url: 'https://api.github.com/users/vsdeeper/events{/privacy}',
          received_events_url: 'https://api.github.com/users/vsdeeper/received_events',
          type: 'User',
          site_admin: false
        },
        html_url: 'https://github.com/vsdeeper/vswift-base',
        description:
          'Public methods and regular library based on typescript, accumulated in common business scenarios at work.',
        fork: false,
        url: 'https://api.github.com/repos/vsdeeper/vswift-base',
        forks_url: 'https://api.github.com/repos/vsdeeper/vswift-base/forks',
        keys_url: 'https://api.github.com/repos/vsdeeper/vswift-base/keys{/key_id}',
        collaborators_url:
          'https://api.github.com/repos/vsdeeper/vswift-base/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/vsdeeper/vswift-base/teams',
        hooks_url: 'https://api.github.com/repos/vsdeeper/vswift-base/hooks',
        issue_events_url:
          'https://api.github.com/repos/vsdeeper/vswift-base/issues/events{/number}',
        events_url: 'https://api.github.com/repos/vsdeeper/vswift-base/events',
        assignees_url: 'https://api.github.com/repos/vsdeeper/vswift-base/assignees{/user}',
        branches_url: 'https://api.github.com/repos/vsdeeper/vswift-base/branches{/branch}',
        tags_url: 'https://api.github.com/repos/vsdeeper/vswift-base/tags',
        blobs_url: 'https://api.github.com/repos/vsdeeper/vswift-base/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/vsdeeper/vswift-base/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/vsdeeper/vswift-base/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/vsdeeper/vswift-base/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/vsdeeper/vswift-base/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/vsdeeper/vswift-base/languages',
        stargazers_url: 'https://api.github.com/repos/vsdeeper/vswift-base/stargazers',
        contributors_url: 'https://api.github.com/repos/vsdeeper/vswift-base/contributors',
        subscribers_url: 'https://api.github.com/repos/vsdeeper/vswift-base/subscribers',
        subscription_url: 'https://api.github.com/repos/vsdeeper/vswift-base/subscription',
        commits_url: 'https://api.github.com/repos/vsdeeper/vswift-base/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/vsdeeper/vswift-base/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/vsdeeper/vswift-base/comments{/number}',
        issue_comment_url:
          'https://api.github.com/repos/vsdeeper/vswift-base/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/vsdeeper/vswift-base/contents/{+path}',
        compare_url: 'https://api.github.com/repos/vsdeeper/vswift-base/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/vsdeeper/vswift-base/merges',
        archive_url: 'https://api.github.com/repos/vsdeeper/vswift-base/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/vsdeeper/vswift-base/downloads',
        issues_url: 'https://api.github.com/repos/vsdeeper/vswift-base/issues{/number}',
        pulls_url: 'https://api.github.com/repos/vsdeeper/vswift-base/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/vsdeeper/vswift-base/milestones{/number}',
        notifications_url:
          'https://api.github.com/repos/vsdeeper/vswift-base/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/vsdeeper/vswift-base/labels{/name}',
        releases_url: 'https://api.github.com/repos/vsdeeper/vswift-base/releases{/id}',
        deployments_url: 'https://api.github.com/repos/vsdeeper/vswift-base/deployments',
        created_at: '2021-12-31T06:01:02Z',
        updated_at: '2022-01-06T10:11:05Z',
        pushed_at: '2022-01-17T02:37:57Z',
        git_url: 'git://github.com/vsdeeper/vswift-base.git',
        ssh_url: 'git@github.com:vsdeeper/vswift-base.git',
        clone_url: 'https://github.com/vsdeeper/vswift-base.git',
        svn_url: 'https://github.com/vsdeeper/vswift-base',
        homepage: null,
        size: 231,
        stargazers_count: 0,
        watchers_count: 0,
        language: 'TypeScript',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        has_discussions: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: null,
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [],
        visibility: 'public',
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: 'master'
      },
      {
        id: 435141091,
        node_id: 'R_kgDOGe-54w',
        name: 'vswift-cli',
        full_name: 'vsdeeper/vswift-cli',
        private: false,
        owner: {
          login: 'vsdeeper',
          id: 15762056,
          node_id: 'MDQ6VXNlcjE1NzYyMDU2',
          avatar_url: 'https://avatars.githubusercontent.com/u/15762056?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/vsdeeper',
          html_url: 'https://github.com/vsdeeper',
          followers_url: 'https://api.github.com/users/vsdeeper/followers',
          following_url: 'https://api.github.com/users/vsdeeper/following{/other_user}',
          gists_url: 'https://api.github.com/users/vsdeeper/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/vsdeeper/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/vsdeeper/subscriptions',
          organizations_url: 'https://api.github.com/users/vsdeeper/orgs',
          repos_url: 'https://api.github.com/users/vsdeeper/repos',
          events_url: 'https://api.github.com/users/vsdeeper/events{/privacy}',
          received_events_url: 'https://api.github.com/users/vsdeeper/received_events',
          type: 'User',
          site_admin: false
        },
        html_url: 'https://github.com/vsdeeper/vswift-cli',
        description: 'Vue swift development scaffolding.',
        fork: false,
        url: 'https://api.github.com/repos/vsdeeper/vswift-cli',
        forks_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/forks',
        keys_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/keys{/key_id}',
        collaborators_url:
          'https://api.github.com/repos/vsdeeper/vswift-cli/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/teams',
        hooks_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/hooks',
        issue_events_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/issues/events{/number}',
        events_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/events',
        assignees_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/assignees{/user}',
        branches_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/branches{/branch}',
        tags_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/tags',
        blobs_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/languages',
        stargazers_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/stargazers',
        contributors_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/contributors',
        subscribers_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/subscribers',
        subscription_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/subscription',
        commits_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/comments{/number}',
        issue_comment_url:
          'https://api.github.com/repos/vsdeeper/vswift-cli/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/contents/{+path}',
        compare_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/merges',
        archive_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/downloads',
        issues_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/issues{/number}',
        pulls_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/milestones{/number}',
        notifications_url:
          'https://api.github.com/repos/vsdeeper/vswift-cli/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/labels{/name}',
        releases_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/releases{/id}',
        deployments_url: 'https://api.github.com/repos/vsdeeper/vswift-cli/deployments',
        created_at: '2021-12-05T10:58:14Z',
        updated_at: '2021-12-30T07:05:39Z',
        pushed_at: '2022-11-11T10:17:09Z',
        git_url: 'git://github.com/vsdeeper/vswift-cli.git',
        ssh_url: 'git@github.com:vsdeeper/vswift-cli.git',
        clone_url: 'https://github.com/vsdeeper/vswift-cli.git',
        svn_url: 'https://github.com/vsdeeper/vswift-cli',
        homepage: '',
        size: 138,
        stargazers_count: 0,
        watchers_count: 0,
        language: 'Vue',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        has_discussions: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: null,
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [],
        visibility: 'public',
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: 'master'
      },
      {
        id: 800288505,
        node_id: 'R_kgDOL7Nu-Q',
        name: 'vswift-components',
        full_name: 'vsdeeper/vswift-components',
        private: false,
        owner: {
          login: 'vsdeeper',
          id: 15762056,
          node_id: 'MDQ6VXNlcjE1NzYyMDU2',
          avatar_url: 'https://avatars.githubusercontent.com/u/15762056?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/vsdeeper',
          html_url: 'https://github.com/vsdeeper',
          followers_url: 'https://api.github.com/users/vsdeeper/followers',
          following_url: 'https://api.github.com/users/vsdeeper/following{/other_user}',
          gists_url: 'https://api.github.com/users/vsdeeper/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/vsdeeper/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/vsdeeper/subscriptions',
          organizations_url: 'https://api.github.com/users/vsdeeper/orgs',
          repos_url: 'https://api.github.com/users/vsdeeper/repos',
          events_url: 'https://api.github.com/users/vsdeeper/events{/privacy}',
          received_events_url: 'https://api.github.com/users/vsdeeper/received_events',
          type: 'User',
          site_admin: false
        },
        html_url: 'https://github.com/vsdeeper/vswift-components',
        description: 'Quickly develop common components based on Vue and Element Plus.',
        fork: false,
        url: 'https://api.github.com/repos/vsdeeper/vswift-components',
        forks_url: 'https://api.github.com/repos/vsdeeper/vswift-components/forks',
        keys_url: 'https://api.github.com/repos/vsdeeper/vswift-components/keys{/key_id}',
        collaborators_url:
          'https://api.github.com/repos/vsdeeper/vswift-components/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/vsdeeper/vswift-components/teams',
        hooks_url: 'https://api.github.com/repos/vsdeeper/vswift-components/hooks',
        issue_events_url:
          'https://api.github.com/repos/vsdeeper/vswift-components/issues/events{/number}',
        events_url: 'https://api.github.com/repos/vsdeeper/vswift-components/events',
        assignees_url: 'https://api.github.com/repos/vsdeeper/vswift-components/assignees{/user}',
        branches_url: 'https://api.github.com/repos/vsdeeper/vswift-components/branches{/branch}',
        tags_url: 'https://api.github.com/repos/vsdeeper/vswift-components/tags',
        blobs_url: 'https://api.github.com/repos/vsdeeper/vswift-components/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/vsdeeper/vswift-components/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/vsdeeper/vswift-components/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/vsdeeper/vswift-components/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/vsdeeper/vswift-components/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/vsdeeper/vswift-components/languages',
        stargazers_url: 'https://api.github.com/repos/vsdeeper/vswift-components/stargazers',
        contributors_url: 'https://api.github.com/repos/vsdeeper/vswift-components/contributors',
        subscribers_url: 'https://api.github.com/repos/vsdeeper/vswift-components/subscribers',
        subscription_url: 'https://api.github.com/repos/vsdeeper/vswift-components/subscription',
        commits_url: 'https://api.github.com/repos/vsdeeper/vswift-components/commits{/sha}',
        git_commits_url:
          'https://api.github.com/repos/vsdeeper/vswift-components/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/vsdeeper/vswift-components/comments{/number}',
        issue_comment_url:
          'https://api.github.com/repos/vsdeeper/vswift-components/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/vsdeeper/vswift-components/contents/{+path}',
        compare_url:
          'https://api.github.com/repos/vsdeeper/vswift-components/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/vsdeeper/vswift-components/merges',
        archive_url:
          'https://api.github.com/repos/vsdeeper/vswift-components/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/vsdeeper/vswift-components/downloads',
        issues_url: 'https://api.github.com/repos/vsdeeper/vswift-components/issues{/number}',
        pulls_url: 'https://api.github.com/repos/vsdeeper/vswift-components/pulls{/number}',
        milestones_url:
          'https://api.github.com/repos/vsdeeper/vswift-components/milestones{/number}',
        notifications_url:
          'https://api.github.com/repos/vsdeeper/vswift-components/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/vsdeeper/vswift-components/labels{/name}',
        releases_url: 'https://api.github.com/repos/vsdeeper/vswift-components/releases{/id}',
        deployments_url: 'https://api.github.com/repos/vsdeeper/vswift-components/deployments',
        created_at: '2024-05-14T03:52:51Z',
        updated_at: '2024-06-29T08:30:24Z',
        pushed_at: '2024-06-29T08:30:20Z',
        git_url: 'git://github.com/vsdeeper/vswift-components.git',
        ssh_url: 'git@github.com:vsdeeper/vswift-components.git',
        clone_url: 'https://github.com/vsdeeper/vswift-components.git',
        svn_url: 'https://github.com/vsdeeper/vswift-components',
        homepage: '',
        size: 421,
        stargazers_count: 0,
        watchers_count: 0,
        language: 'Vue',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        has_discussions: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: null,
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [],
        visibility: 'public',
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: 'master'
      },
      {
        id: 587121249,
        node_id: 'R_kgDOIv7CYQ',
        name: 'vswift-demo',
        full_name: 'vsdeeper/vswift-demo',
        private: false,
        owner: {
          login: 'vsdeeper',
          id: 15762056,
          node_id: 'MDQ6VXNlcjE1NzYyMDU2',
          avatar_url: 'https://avatars.githubusercontent.com/u/15762056?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/vsdeeper',
          html_url: 'https://github.com/vsdeeper',
          followers_url: 'https://api.github.com/users/vsdeeper/followers',
          following_url: 'https://api.github.com/users/vsdeeper/following{/other_user}',
          gists_url: 'https://api.github.com/users/vsdeeper/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/vsdeeper/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/vsdeeper/subscriptions',
          organizations_url: 'https://api.github.com/users/vsdeeper/orgs',
          repos_url: 'https://api.github.com/users/vsdeeper/repos',
          events_url: 'https://api.github.com/users/vsdeeper/events{/privacy}',
          received_events_url: 'https://api.github.com/users/vsdeeper/received_events',
          type: 'User',
          site_admin: false
        },
        html_url: 'https://github.com/vsdeeper/vswift-demo',
        description: 'Quick monorepo framework demo.',
        fork: false,
        url: 'https://api.github.com/repos/vsdeeper/vswift-demo',
        forks_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/forks',
        keys_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/keys{/key_id}',
        collaborators_url:
          'https://api.github.com/repos/vsdeeper/vswift-demo/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/teams',
        hooks_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/hooks',
        issue_events_url:
          'https://api.github.com/repos/vsdeeper/vswift-demo/issues/events{/number}',
        events_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/events',
        assignees_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/assignees{/user}',
        branches_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/branches{/branch}',
        tags_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/tags',
        blobs_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/languages',
        stargazers_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/stargazers',
        contributors_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/contributors',
        subscribers_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/subscribers',
        subscription_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/subscription',
        commits_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/comments{/number}',
        issue_comment_url:
          'https://api.github.com/repos/vsdeeper/vswift-demo/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/contents/{+path}',
        compare_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/merges',
        archive_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/downloads',
        issues_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/issues{/number}',
        pulls_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/milestones{/number}',
        notifications_url:
          'https://api.github.com/repos/vsdeeper/vswift-demo/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/labels{/name}',
        releases_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/releases{/id}',
        deployments_url: 'https://api.github.com/repos/vsdeeper/vswift-demo/deployments',
        created_at: '2023-01-10T02:14:27Z',
        updated_at: '2024-07-14T09:47:45Z',
        pushed_at: '2024-02-26T01:57:44Z',
        git_url: 'git://github.com/vsdeeper/vswift-demo.git',
        ssh_url: 'git@github.com:vsdeeper/vswift-demo.git',
        clone_url: 'https://github.com/vsdeeper/vswift-demo.git',
        svn_url: 'https://github.com/vsdeeper/vswift-demo',
        homepage: '',
        size: 23,
        stargazers_count: 6,
        watchers_count: 6,
        language: 'TypeScript',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        has_discussions: false,
        forks_count: 1,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: null,
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [],
        visibility: 'public',
        forks: 1,
        open_issues: 0,
        watchers: 6,
        default_branch: 'master'
      }
    ]
  }
}
